language: perl
sudo: false
perl:
  - "5.24"
  - "5.26"
  - "dev"
matrix:
  include:
    - perl: "5.24"
      env: COVERAGE=1
  allow_failures:
    - perl: dev
before_install:
  - curl -sL --compressed https://git.io/cpm | perl - install Alien::V8
  - eval $(curl https://travis-perl.github.io/init) --auto
