language: perl
sudo: false
perl:
  - "5.16"
  - "5.18"
  - "5.20"
  - "5.22"
  - "5.24"
  - "5.26"
  - "dev"
matrix:
  include:
    - perl: "5.24"
      env: COVERAGE=1
  allow_failures:
    - perl: dev
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install libv8-dev
  - eval $(curl https://travis-perl.github.io/init) --auto
